repos:
  # pre-commit hooks
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.22.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/life4/flakehell
    rev: v.0.7.1
    hooks:
      - id: flakehell
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: pipenv run type-check
        language: system
        pass_filenames: false
        types: [python]
      - id: pytest
        name: pytest
        entry: pipenv run test
        language: system
        pass_filenames: false
        always_run: true

  # commit-msg hooks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
      - id: gitlint
